global using Narumikazuchi.Collections;
global using Narumikazuchi.InputOutput;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics.CodeAnalysis;
global using System.Diagnostics.Contracts;
global using System.IO;
global using System.Linq;